
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'EFEITO ELEMENTO ESTADO\n    encantamento : ELEMENTO estados efeitos  \n                 | ELEMENTO efeitos          \n    \n    estados : ESTADO  \n    \n    efeitos : EFEITO                \n            | EFEITO EFEITO         \n            | EFEITO EFEITO EFEITO  \n    '
    
_lr_action_items = {'ELEMENTO':([0,],[2,]),'$end':([1,4,6,7,8,9,],[0,-2,-4,-1,-5,-6,]),'ESTADO':([2,],[5,]),'EFEITO':([2,3,5,6,8,],[6,6,-3,8,9,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'encantamento':([0,],[1,]),'estados':([2,],[3,]),'efeitos':([2,3,],[4,7,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> encantamento","S'",1,None,None,None),
  ('encantamento -> ELEMENTO estados efeitos','encantamento',3,'p_encantamento','Encantorium.py',32),
  ('encantamento -> ELEMENTO efeitos','encantamento',2,'p_encantamento','Encantorium.py',33),
  ('estados -> ESTADO','estados',1,'p_estados','Encantorium.py',43),
  ('efeitos -> EFEITO','efeitos',1,'p_efeitos','Encantorium.py',50),
  ('efeitos -> EFEITO EFEITO','efeitos',2,'p_efeitos','Encantorium.py',51),
  ('efeitos -> EFEITO EFEITO EFEITO','efeitos',3,'p_efeitos','Encantorium.py',52),
]
