
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftVELleftINTRAleftETrightINTENSIDADEEFEITO ELEMENTO ESTADO ET INTENSIDADE INTRA LPAREN RPAREN VELexpressao_magica : expressao_magica VEL expressao_magica\n                        | expressao_magica INTRA expressao_magica\n                        | expressao_magica ET expressao_magicaexpressao_magica : INTENSIDADE expressao_magicaexpressao_magica : LPAREN expressao_magica RPARENexpressao_magica : encantamentoencantamento : ELEMENTO ESTADO lista_efeitosencantamento : ELEMENTO lista_efeitoslista_efeitos : EFEITO lista_efeitoslista_efeitos : EFEITO'
    
_lr_action_items = {'INTENSIDADE':([0,2,3,6,7,8,],[2,2,2,2,2,2,]),'LPAREN':([0,2,3,6,7,8,],[3,3,3,3,3,3,]),'ELEMENTO':([0,2,3,6,7,8,],[5,5,5,5,5,5,]),'$end':([1,4,9,12,13,14,15,16,17,18,19,],[0,-6,-4,-8,-10,-1,-2,-3,-5,-7,-9,]),'VEL':([1,4,9,10,12,13,14,15,16,17,18,19,],[6,-6,-4,6,-8,-10,-1,-2,-3,-5,-7,-9,]),'INTRA':([1,4,9,10,12,13,14,15,16,17,18,19,],[7,-6,-4,7,-8,-10,7,-2,-3,-5,-7,-9,]),'ET':([1,4,9,10,12,13,14,15,16,17,18,19,],[8,-6,-4,8,-8,-10,8,8,-3,-5,-7,-9,]),'RPAREN':([4,9,10,12,13,14,15,16,17,18,19,],[-6,-4,17,-8,-10,-1,-2,-3,-5,-7,-9,]),'ESTADO':([5,],[11,]),'EFEITO':([5,11,13,],[13,13,13,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expressao_magica':([0,2,3,6,7,8,],[1,9,10,14,15,16,]),'encantamento':([0,2,3,6,7,8,],[4,4,4,4,4,4,]),'lista_efeitos':([5,11,13,],[12,18,19,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expressao_magica","S'",1,None,None,None),
  ('expressao_magica -> expressao_magica VEL expressao_magica','expressao_magica',3,'p_expressao_magica_binop','encantorium.py',40),
  ('expressao_magica -> expressao_magica INTRA expressao_magica','expressao_magica',3,'p_expressao_magica_binop','encantorium.py',41),
  ('expressao_magica -> expressao_magica ET expressao_magica','expressao_magica',3,'p_expressao_magica_binop','encantorium.py',42),
  ('expressao_magica -> INTENSIDADE expressao_magica','expressao_magica',2,'p_expressao_magica_unary','encantorium.py',46),
  ('expressao_magica -> LPAREN expressao_magica RPAREN','expressao_magica',3,'p_expressao_magica_group','encantorium.py',50),
  ('expressao_magica -> encantamento','expressao_magica',1,'p_expressao_magica_encantamento','encantorium.py',54),
  ('encantamento -> ELEMENTO ESTADO lista_efeitos','encantamento',3,'p_encantamento_estado','encantorium.py',58),
  ('encantamento -> ELEMENTO lista_efeitos','encantamento',2,'p_encantamento_simples','encantorium.py',62),
  ('lista_efeitos -> EFEITO lista_efeitos','lista_efeitos',2,'p_lista_efeitos_recursivo','encantorium.py',66),
  ('lista_efeitos -> EFEITO','lista_efeitos',1,'p_lista_efeitos_base','encantorium.py',70),
]
